### ISSUE TITLE
error

### ISSUE THREAD

**Issue by loopy-iri** [U7P4L-IN/ENCODE#4]
Traceback (most recent call last):
  File "/sdcard/e-ENC.py", line 9, in <module>
  File "<string>", line 1, in <module>
  File "<x>", line 1, in <module>
  File "<x>", line 1, in <module>
  File "<x>", line 1, in <module>
  File "<x>", line 1, in <module>
  File "<x>", line 233, in <module>
  File "<x>", line 89, in my_menu
  File "<x>", line 217, in MainMenu
  File "C:\Users\NPC\AppData\Local\Programs\Python\Python311\Lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeDecodeError: 'charmap' codec can't decode byte 0x8f in position 770: character maps to <undefined>

**Comment by U7P4L-IN** [comment]
Share your issue ss

**Comment by loopy-iri** [comment]
![image](https://github.com/user-attachments/assets/4bee3e35-79bb-467b-be89-bc7e4bc3eebd)

**Comment by loopy-iri** [comment]
cpython
